server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/jiaochengdemo?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

